### ISSUE TITLE
Add more info to the description of this mod.

### ISSUE THREAD

**Issue by JENOVAAbsolute** [BansheeStudio/PokemonWildsGen3Overhaul#2]
This mod adds modded pokemon, and there is nothing saying as such in the description. This is a problem. What will happen if the legendaries you modded in are added officially by the devs? Multiple people have stated they could no longer load their saves after removing your mod. 

Hopefully there will be a way to remove these mons safely in the future, but for now, I suggest updating the description to let people know exactly what they're downloading. Regardless of my gripes, the 3rd gen overhaul has made the experience much better. I appreciate your work.

**Comment by BansheeStudio** [comment]
hi thanks for submitting an issues yes this mod does add in modded mons from what we take of it, it makes the missing mons spawn-able and unlocks then we think there will not be any issues updating for unlocking modded mons
but we will put there will be a huge issue for this mod for 0.9 as 0.9 will change everything menus, music, tile names and folders, 0.9 will change so much of wilds this mod will probably not be compatible sadly though that being said we will keep the 0.8 version up on github and label it as Classic Version do not worry about 0.9 as our team is working on a newer version and we are tying to get into contact with the lead devs to lend us a per-realse of 0.9 so we can port the mod and have it ready for 0.9 release date
we will update the mod to let user know that it connect unplugged features in the description & thank you for using our mod if there is any other issues please do not hesitate to submit them on our github
